# fly.toml app configuration file generated for part3-weathered-breeze-6177 on 2025-08-27T00:10:37-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "part3-weathered-breeze-6177"
primary_region = "gig"

[build]

[env]
PORT = "3001"

[http_service]
internal_port = 3001
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[[vm]]
memory = "1gb"
cpu_kind = "shared"
cpus = 1
